namespace Kellox.Exceptions
{
    //continue exception (forces next iteration of the loop)
    internal class Continue : ApplicationException
    {

    }
}